language: python

python: 2.7

env:
  - DJANGO="Django<1.9"  # Django 1.8.x
  - DJANGO="Django<1.10" # Django 1.9.x

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r test_requirements.txt --use-mirrors

# command to run tests
script: env PYTHONPATH=$PWD django-admin.py test --settings=test_settings

# submit coverage reports
after_success:
  - coveralls
